### ISSUE TITLE
Route onboarding "Customize site" links to new site editor when theme is FSE

### ISSUE THREAD

**Issue by wpalani** [bluehost/bluehost-wordpress-plugin#330]
**Is your feature request related to a problem? Please describe.**
Currently, if the active theme is FSE, the customize my site links route to the legacy customizer, where no options exist to edit the site.

**Describe the solution you'd like**
Detect if the active theme is an FSE theme and route onboarding links to the new site editor experience.

![ezgif-4-c4b4d3c40f](https://user-images.githubusercontent.com/38976631/222201493-8971b81f-984d-44ee-be80-d761e5f388ea.gif)

**Comment by earnjam** [comment]
Hey @wpalani I think this isn't working correctly. When I click the link, I get:
```
{
  "code": "rest_forbidden_context",
  "message": "Sorry, you are not allowed to access this endpoint.",
  "data": {
    "status": 401
  }
}
```

The REST API permissions check is failing here because the user is not set. For cookie-based auth, we need to have the `X-WP-Nonce` header included in the API request. That protection is to help prevent CSRF issues.

I think there are a few options: 
- Make an admin-ajax action (or other admin page) simple redirect we can hit that performs the same theme logic check
- Turn this button action into an AJAX call ensuring the `X-WP-Nonce` header is included, and then do a `window.location.href` based on the response. 
- Evaluate the proper href location of the link at page load time and set it at render

**Comment by wpalani** [comment]
Hey @earnjam I just opened a PR to address this: https://github.com/bluehost/bluehost-wordpress-plugin/pull/415

**Comment by circlecube** [comment]
This looks to be complete since that PR has been merged. Closing
